### ISSUE TITLE
Attachments not actually being copied into g drive

### ISSUE THREAD

**Issue by mgslone** [ahochsteger/gmail-processor#97] opened 2023-08-23 15:29 UTC
I'm getting "ok": false, which seems to indicate an error, but I'm given no specifics.
The files do not appear anywhere in my google drive after running this.
It also seems odd that it's marking messages as read (which is working), even though I didn't tell it to.

Using the following config:

```
const resumesToGdrive = {
  settings: {
    // Place settings here
  },
  global: {
    // Place global thread, message or attachment configuration here
  },
  threads: [
    // Place thread processing config here
    {
      match: {
        query: "from:no-reply@breezy-mail.com has:attachment after:2023/08/22"
      },
      attachments: [
        {
          match: {
            name: ".*\.pdf$",
          },
          actions: [
            {
              name: "attachment.store",
              args: {
                conflictStrategy: 'skip',
                location: "auto-resumes/${message.date:format:yyyy-MM-dd}.${attachment.name}",
                description: "${message.subject}"
              },
            },
          ],
        },
      ],
    },
  ],
}

function processResumeEmails() {
  GmailProcessorLib.run(resumesToGdrive, 'safe-mode');
}
```

The output I get for an individual entry looks like so:
```
11:24:15 AM	Info	[2023-08-23T15:24:15.412Z] INFO: Processing of thread id 18a22e7af2afc6e2 (subject:'fname lname applied to Senior Web Rendering Engineer') started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.413Z] INFO: Processing of message config '' started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.420Z] DEBUG: Testing regex matches for key prefix message ...
11:24:15 AM	Info	[2023-08-23T15:24:15.421Z] DEBUG: Testing regex match for from ...
11:24:15 AM	Info	[2023-08-23T15:24:15.422Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.423Z] DEBUG: Testing regex match for subject ...
11:24:15 AM	Info	[2023-08-23T15:24:15.424Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.425Z] DEBUG: Testing regex match for to ...
11:24:15 AM	Info	[2023-08-23T15:24:15.426Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.427Z] DEBUG: ... result for message.matched: true
11:24:15 AM	Info	[2023-08-23T15:24:15.429Z] INFO: Processing of message id 18a22e7af2afc6e2 (date:'2023-08-23T14:58:43.000Z',  subject:'fname lname applied to Senior Web Rendering Engineer', from:Breezy HR <no-reply@breezy-mail.com>) started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.430Z] INFO: Processing of attachment config '' started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.473Z] DEBUG: Testing regex matches for key prefix attachment ...
11:24:15 AM	Info	[2023-08-23T15:24:15.474Z] DEBUG: Testing regex match for name ...
11:24:15 AM	Info	[2023-08-23T15:24:15.475Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.476Z] DEBUG: Testing regex match for contentType ...
11:24:15 AM	Info	[2023-08-23T15:24:15.478Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.479Z] DEBUG: ... result for attachment.matched: true
11:24:15 AM	Info	[2023-08-23T15:24:15.481Z] INFO: Processing of attachment hash '8549ab83_96483860_cafbd727_14246a03_5b5f25a5' (name:'Breezy Profile - fname lname.pdf', type:application/pdf, size:26469) started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.482Z] INFO: Executing action 'attachment.store' with args: {"conflictStrategy":"skip","location":"auto-resumes/${message.date:format:yyyy-MM-dd}.${attachment.name}","description":"${message.subject}"}
11:24:15 AM	Info	[2023-08-23T15:24:15.483Z] DEBUG: Calling method 'store' ...
11:24:15 AM	Info	[2023-08-23T15:24:15.506Z] INFO: Storing attachment 'Breezy Profile - fname lname.pdf' to 'auto-resumes/2023-08-23.Breezy Profile - fname lname.pdf' ...
11:24:15 AM	Info	[2023-08-23T15:24:15.508Z] INFO: Action result: {"ok":false,"error":{}}
11:24:15 AM	Info	[2023-08-23T15:24:15.509Z] INFO: Processing of attachment hash '8549ab83_96483860_cafbd727_14246a03_5b5f25a5' finished.
11:24:15 AM	Info	[2023-08-23T15:24:15.511Z] DEBUG: Testing regex matches for key prefix attachment ...
11:24:15 AM	Info	[2023-08-23T15:24:15.511Z] DEBUG: Testing regex match for name ...
11:24:15 AM	Info	[2023-08-23T15:24:15.512Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.513Z] DEBUG: Testing regex match for contentType ...
11:24:15 AM	Info	[2023-08-23T15:24:15.514Z] DEBUG: ... matches
11:24:15 AM	Info	[2023-08-23T15:24:15.515Z] DEBUG: ... result for attachment.matched: true
11:24:15 AM	Info	[2023-08-23T15:24:15.516Z] INFO: Processing of attachment hash 'cccbae0a_c4f4e820_35e21a2e_1542c662_b4d09f4d' (name:'fnamelname.pdf', type:application/pdf, size:77370) started ...
11:24:15 AM	Info	[2023-08-23T15:24:15.517Z] INFO: Executing action 'attachment.store' with args: {"conflictStrategy":"skip","location":"auto-resumes/${message.date:format:yyyy-MM-dd}.${attachment.name}","description":"${message.subject}"}
11:24:15 AM	Info	[2023-08-23T15:24:15.518Z] DEBUG: Calling method 'store' ...
11:24:15 AM	Info	[2023-08-23T15:24:15.522Z] INFO: Storing attachment 'fnamelname.pdf' to 'auto-resumes/2023-08-23.fnamelname.pdf' ...
11:24:15 AM	Info	[2023-08-23T15:24:15.523Z] INFO: Action result: {"ok":false,"error":{}}
11:24:15 AM	Info	[2023-08-23T15:24:15.524Z] INFO: Processing of attachment hash 'cccbae0a_c4f4e820_35e21a2e_1542c662_b4d09f4d' finished.
11:24:15 AM	Info	[2023-08-23T15:24:15.524Z] INFO: Processing of attachment config '' finished.
11:24:15 AM	Info	[2023-08-23T15:24:15.525Z] INFO: Executing action 'message.markRead' with args: {}
11:24:15 AM	Info	[2023-08-23T15:24:15.526Z] DEBUG: Calling method 'markRead' ...
11:24:15 AM	Info	[2023-08-23T15:24:15.527Z] INFO: Marking message 'fname lname applied to Senior Web Rendering Engineer' as read ...
11:24:15 AM	Info	[2023-08-23T15:24:15.676Z] INFO: Action result: {"message":{}}
11:24:15 AM	Info	[2023-08-23T15:24:15.679Z] INFO: Processing of message id 18a22e7af2afc6e2 finished.
11:24:15 AM	Info	[2023-08-23T15:24:15.680Z] INFO: Processing of message config '' finished.
11:24:15 AM	Info	[2023-08-23T15:24:15.681Z] INFO: Processing of thread id 18a22e7af2afc6e2 finished.
```

**Comment by ahochsteger** [comment] 2023-08-23 15:44
Thanks for reporting, I'll have a look at it will get back to you with a fix.
Andreas

**Comment by ahochsteger** [comment] 2023-08-25 10:18
Since I cannot reproduce the issue on my side I tend to think it has to do with some permissions not being properly handled.
Therefore I created an end-to-end test suite that creates some emails with attachments and uses them to perform automated tests.

It would be great, if you could execute these two files to better narrow the issue down:
* This creates the emails for the tests: <https://github.com/ahochsteger/gmail-processor/blob/main/src/gas/examples/e2eInit.js>
* And this runs the tests: <https://github.com/ahochsteger/gmail-processor/blob/main/src/gas/examples/e2eTest01.js>

Also please let me know the list of Project OAuth Scopes your Google Apps Script project lists on the overview page.

**Comment by sauravhiremath** [comment] 2023-08-26 10:39
Thanks @ahochsteger for creating the e2e tests, I was running into similar issue. I ran it on my side, and it worked perfectly

Upon closer inspection, the issue lies how we specify the location. Apparently a trailing `/` is required. Fixed this and it works!

corrected
```
location: "/auto-resumes/${message.date:format:yyyy-MM-dd}.${attachment.name}",
```

original
```
location: "auto-resumes/${message.date:format:yyyy-MM-dd}.${attachment.name}",
```

Maybe we can consider adding this to the documentation?

**Comment by ahochsteger** [comment] 2023-08-26 12:25
@sauravhiremath thanks for finding that out, I'll release a fix later today so locations without a leading slash will work too.

**Comment by ahochsteger** [comment] 2023-08-27 07:24
@sauravhiremath @plattze @mgslone v2.0.3 should fix the issue of locations without leading slashes.
It would be great, if someone could confirm that so I can close the issue.

**Comment by ahochsteger** [comment] 2023-09-07 08:56
Since v2.0.3 fixed the issue I'll close it.

**Closed** 2023-09-07 08:56 UTC
Labels: bug
